# Generated by Django 3.0.5 on 2021-08-19 22:28

from django.db import migrations

def create_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Teacher = apps.get_model('education', 'Teacher')
    for teacher in Teacher.objects.all():
        teacher.first_name = "Ivan"
        teacher.last_name = "Romanenko"
        teacher.save()

    Student = apps.get_model('education', 'Student')
    for student in Student.objects.all():
        student.first_name = "Aleksandr"
        student.last_name = "Golobokov"
        student.save()

    Homework = apps.get_model('education', 'Homework')
    for homework in Homework.objects.all():
        homework.text_of_homework = "Bla bla bla"
        # homework.deadline =
        # homework.created =
        homework.save()

    HomeworkResult = apps.get_model('education', 'Homework')
    for homework_result in HomeworkResult.objects.all():
        homework_result.author = Student
        homework_result.homework = Homework
        homework_result.solution = 'Done'
        homework_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
